update yinstall: debug version

diff --git a/yinstall b/yinstall
--- a/yinstall
+++ b/yinstall
@@ -7,7 +7,7 @@
 #   user needs to select usual items for the install (like language,...)
 #
 
-Y_VER="0.96"
+Y_VER="0.97"
 MODE_NEWSYS="new_system"
 MODE_MIG="migrate"
 
@@ -27,14 +27,18 @@ Y_ORIG_MNT="/mnt"
 Y_BKP_SRV="bp-nas"
 Y_BKP_USER="jenov"
 Y_BKP_PATH="/volume1/backup/tmp"
-Y_FILENAME="test"
+Y_FILENAME="test.tar"
+
+Y_FS_ROOT="ext4"
+Y_FS_BOOT="ext2"
 
 # ============================================================================
 
 # command line inputs 
 while [ -n "$1" ]; do
     case $1 in
-        --help|-h)      echo "Usage: $0 [-d] [-n] [-l] [-h]"; exit 0;;
+        --help|-h)      echo "Usage: $0 [-D] [-N] [-l] [-f] [-h]";
+                        echo "see script for more options"; exit 0;;
         --migrate|-m)   Y_MODE="$MODE_MIG";;
         --dev|-d)       test -n "$2" && Y_DEV="$2"; shift;;
         --o_root|-o)    test -n "$2" && Y_ORIG_ROOT="$2"; shift;;
@@ -66,9 +70,8 @@ yrun () {
         OUT="/dev/null"
     fi
     test -z "$Y_DRY_RUN" && {
-        test -n "$FOUT" && OUT=$FOUT
-        if [ -n "$NOREDIR" ]; then
-            $* 2>>$Y_LOG
+        if [ -n "$FOUT" ]; then
+            $* >>$FOUT 2>>$Y_LOG
         else
             $* >>$OUT 2>>$Y_LOG
         fi
@@ -85,7 +88,7 @@ Y_ROOT="3"
 Y_LABEL="msdos"
 
 # backup system before migration
-test "$Y_MODE_" = "$MODE_MIG" && {
+test "$Y_MODE" = "$MODE_MIG" && {
     yrun sudo mount $Y_ORIG_ROOT $Y_ORIG_MNT
     yrun sudo mount --bind /dev $Y_ORIG_MNT/dev
     UMOUNT="$Y_ORIG_MNT"
@@ -132,12 +135,12 @@ yrun sudo parted --script $Y_DEV mkpart primary ext2  $Y_START $Y_END
 yrun sudo parted --script $Y_DEV set $Y_BOOT "boot" on 
 
 # setup filesystems
-yrun sudo mkfs.ext2 -F ${Y_DEV}$Y_BOOT
+yrun sudo mkfs.${Y_FS_BOOT} -F ${Y_DEV}$Y_BOOT
 yrun sudo mkswap -f ${Y_DEV}$Y_SWAP
 echo $Y_ROOT_PASSWD | yrun sudo cryptsetup --cipher=aes-xts-plain --key-size=256 luksFormat ${Y_DEV}$Y_ROOT
 echo $Y_ROOT_PASSWD | yrun sudo cryptsetup luksOpen ${Y_DEV}$Y_ROOT $Y_ROOT_NAME
 yrun sudo cryptsetup -v status $Y_ROOT_NAME
-yrun sudo mkfs.ext4 -F /dev/mapper/$Y_ROOT_NAME
+yrun sudo mkfs.${Y_FS_ROOT} -F /dev/mapper/$Y_ROOT_NAME
 
 # run GUI based installation for new system setup
 test "$Y_MODE" = "$MODE_NEWSYS" && {
@@ -174,18 +177,28 @@ yrun sudo mount --bind /dev dev
 yrun sudo mount --bind /sys sys
 yrun sudo mount -t proc proc proc
 
-TMP="/tmp/ydev"
-yrun rm -f $TMP
-FOUT=$TMP
-yrun blkid -o export ${Y_DEV}$Y_ROOT
-FOUT=""
+TMP="/tmp/ytmp"
 
-test -e $TMP || sleep 1
-yrun source $TMP
-yrun cat $TMP
-yrun rm -f $TMP
 FOUT=$TMP
-yrun echo root UUID=$UUID none luks
+yrun sudo blkid -o export ${Y_DEV}$Y_ROOT
+
+#while [ ! -s "$TMP" -a -z "$Y_DRY_RUN" ] ; do 
+#    echo DEBUG: waiting...; 
+#    sleep 1; 
+#done
+#test -z "$Y_DRY_RUN" && {
+#    echo "DEBUG: cat $TMP"
+#    cat $TMP 
+#}
+yrun source $TMP
+test -z "$Y_DRY_RUN" -a -z "$UUID" && { 
+    echo "FATAL ERROR: UUID is empty" | tee -a $Y_LOG
+#    echo "DEBUG: TMP=$TMP; FOUT=$FOUT"
+    cat $TMP | tee -a $Y_LOG
+    exit 1
+}
+yrun rm -f $TMP
+yrun echo root UUID=${UUID} none luks
 FOUT=""
 
 yrun cat $TMP
@@ -194,15 +207,16 @@ yrun sudo cp $TMP /mnt/etc/crypttab
 # make sure we have all essentials
 yrun sudo cp /etc/resolv.conf $Y_ORIG_MNT/etc
 yrun sudo chroot $Y_ORIG_MNT apt-get install --yes cryptsetup
-yrun sudo chroot $Y_ORIG_MNT apt-get install --yes grub2
+#yrun sudo chroot $Y_ORIG_MNT apt-get install --yes grub2
 
 # update system
 yrun rm -f $TMP
-FOUT=$TMP
-yrun echo $Y_ORIG_ROOT  /     ext4 errors=remount-ro 0 1
-yrun echo $Y_DEV$Y_BOOT /boot ext2 defaults 0 2
+FOUT="$TMP"
+yrun echo $Y_ORIG_ROOT  /     $Y_FS_ROOT errors=remount-ro 0 1
+yrun echo $Y_DEV$Y_BOOT /boot $Y_FS_BOOT defaults 0 2
 yrun echo $Y_DEV$Y_SWAP none  sw 0 0
 FOUT=""
+
 yrun sudo cp $TMP $Y_ORIG_MNT/etc/fstab
 
 yrun sudo chroot $Y_ORIG_MNT update-grub
