update yinstall V0.99

diff --git a/yinstall b/yinstall
--- a/yinstall
+++ b/yinstall
@@ -1,19 +1,17 @@
 #/bin/bash
 # script has two modes
 #   new_system mode: creates an encrypted installation of install media 
-#   migrate mode: backups up current system, repartition disk and reinstalls it
+        #   migrate mode: backups up current system, repartition disk and reinstalls it
 #  Limitations: 
 #   user needs to set partitions mounting points and fs type
 #   user needs to select usual items for the install (like language,...)
 #
-# TODO Y_ORIG_ROOT used in backup and new system setup as well, 
-#   need to be separated, so different device can be defind
-# TODO verify backup and restore
-# TODO create checksums
+# TODO add backup and restore verification
+# TODO create and store checksums
 # TODO need to release block devide before repartition 
 #   when original and new system is on the same device
 
-Y_VER="0.98"
+Y_VER="0.99"
 MODE_NEWSYS="new_system"
 MODE_MIG="migrate"
 
@@ -30,6 +28,7 @@ Y_ROOT_PASSWD="csolnok"
 Y_ORIG_ROOT="/dev/mapper/root"
 Y_ORIG_MOUNT=""
 Y_ORIG_MNT="/mnt"
+Y_NEW_ROOT="/dev/mapper/root"
 Y_BKP_SRV="bp-nas"
 Y_BKP_USER="jenov"
 Y_BKP_PATH="/volume1/backup/tmp"
@@ -38,6 +37,8 @@ Y_FILENAME="test.tar"
 Y_FS_ROOT="ext4"
 Y_FS_BOOT="ext2"
 
+Y_ERROR_CONSOLE="true"
+Y_EPS1="\[\033[01;31m\]FIXME#\[\033[00m\] " 
 # ============================================================================
 
 # command line inputs 
@@ -47,8 +48,9 @@ while [ -n "$1" ]; do
                         echo "see script for more options"; exit 0;;
         --migrate|-m)   Y_MODE="$MODE_MIG";;
         --dev|-d)       test -n "$2" && Y_DEV="$2"; shift;;
-        --o_root|-o)    test -n "$2" && Y_ORIG_ROOT="$2"; shift;;
+        --o_root|-or)   test -n "$2" && Y_ORIG_ROOT="$2"; shift;;
         --o_mount|-M)   test -n "$2" && Y_ORIG_MOUNT="$2"; shift;;
+        --n_root|-nr)   test -n "$2" && Y_NEW_ROOT="$2"; shift;;
         --b_user|-u)    test -n "$2" && Y_BKP_USER="$2"; shift;;
         --filename|-f)  test -n "$2" && Y_FILENAME=$2; shift;;
         --debug|-D)     Y_DEBUG="true";;
@@ -66,6 +68,11 @@ echo VER=$Y_VER, DEBUG=$Y_DEBUG, \
 MODE=$Y_MODE, LOG=$Y_LOG, DRY_RUN=$Y_DRY_RUN | tee -a $Y_LOG
 
 # help funtion(s)
+y_error_console(){
+    echo E#
+    return 1
+}
+
 # run function that checks sucessful command exit status and breaks if not
 yrun () {
     if [ "$Y_DEBUG" = "true" ] ; then {
@@ -81,7 +88,15 @@ yrun () {
         else
             $* >>$OUT 2>>$Y_LOG
         fi
-        test "$?" = "0" || { echo "FATAL ERROR" | tee -a $Y_LOG; exit 1; }
+        test "$?" = "0" || { 
+            echo "FATAL ERROR" | tee -a $Y_LOG
+            if [ "$Y_ERROR_CONSOLE" = "true" ] ; then
+                bash --rcfile <(echo "PS1='$Y_EPS1'") -i
+                test "$?" = "0" || exit 1
+            else
+                exit 1
+            fi
+        }
     }
     return 0
 }
@@ -118,14 +133,18 @@ test "$Y_MODE" = "$MODE_MIG" && {
         sudo tar -c $Y_ORIG_MNT 2>>$Y_LOG | \
         ssh $Y_BKP_USER@$Y_BKP_SRV FILE=$Y_FILENAME VAR=$Y_BKP_PATH \
         'X=$VAR; Y=$FILE; cat > ${X}/${Y}'
+    test -z "$Y_DRY_RUN" &&
+        ssh $Y_BKP_USER@$Y_BKP_SRV FILE=$Y_FILENAME VAR=$Y_BKP_PATH \
+        'X=$VAR; Y=$FILE; md5sum ${X}/${Y} > ${X}/${Y}.md5sum'
     
-    # FIXME verify backup
-
     yrun sudo umount $UMOUNT
 }
 
 # -----------------------------------------------------------------------------
 # setup new partitions on system disk
+
+yrun sudo umount -l -A $Y_ORIG_MNT
+#yrun sudo dd if=/dev/zero of=$Y_DEV count=1M
 
 yrun sudo parted --script $Y_DEV mklabel $Y_LABEL
 
@@ -158,7 +177,7 @@ test "$Y_MODE" = "$MODE_NEWSYS" && {
 # restore or fix up installed image
 yrun sudo mount /dev/mapper/$Y_ROOT_NAME $Y_ORIG_MNT
 yrun cd $Y_ORIG_MNT
-yrun sudo mkdir boot
+yrun sudo mkdir -p boot
 yrun sudo mount ${Y_DEV}$Y_BOOT boot
 
 test "$Y_MODE" = "$MODE_MIG" && {
@@ -204,7 +223,7 @@ yrun sudo chroot $Y_ORIG_MNT apt-get install --yes cryptsetup
 yrun rm -f $TMP
 
 FOUT="$TMP"
-    yrun echo $Y_ORIG_ROOT  /     $Y_FS_ROOT errors=remount-ro 0 1
+    yrun echo $Y_NEW_ROOT  /     $Y_FS_ROOT errors=remount-ro 0 1
     yrun echo $Y_DEV$Y_BOOT /boot $Y_FS_BOOT defaults 0 2
     yrun echo $Y_DEV$Y_SWAP none  sw 0 0
 FOUT=""
