update ymake_dev

diff --git a/ymake_dev b/ymake_dev
--- a/ymake_dev
+++ b/ymake_dev
@@ -1,5 +1,5 @@
-# vim: ts=4:sw=4
 #!/bin/bash
+# vim: ts=4:sw=4
 # Based on template.src version 1.2 last modified 2006.09.29 by y
 # Add your description here of the program here!
 
@@ -30,6 +30,7 @@ LAST_MOD="2017.02.02"
 
 # Define log file here
 LOG="/tmp/${0##*/}.log"
+Y_LOG="$LOG"
 
 # Uncomment this if you need debug enabled
 #Y_DEBUG="true"
@@ -42,9 +43,34 @@ LOG="/tmp/${0##*/}.log"
 # -------------- configuration defaults -----------------------
 Y_DEV_DEV="/dev/sdb3"
 Y_DEV_MNT="/xy"
+Y_EPS1="\[\033[01;31m\]FIXME#\[\033[00m\] "
+Y_ERROR_CONSOLE="true"
 
+# run function that checks sucessful command exit status and breaks if not
+y_run_ (){
+    while true; do
+        y_run $*
+        RET="$?"
+        test "$RET" = "0" || {
+            y_info "'$*' command returned: $RET"
+            if [ "$Y_ERROR_CONSOLE" = "true" ] ; then
+                bash --rcfile <(echo "PS1='$Y_EPS1'") -i
+                RET="$?"
+                case "$RET" in
+                    0) echo SKIP: "$*"; return;;
+                    1) echo RETRY: "$*"; continue;;
+                    2) echo EXIT on ERROR; exit "$RET";;
+                esac
+            else
+                exit "$RET"
+            fi
+        }
+    done
+}
+
+# mount and store for cleanup
 y_mount(){
-    y_run mount "$*"
+    y_run_ mount "$*"
     test -z "$Y_DRY_RUN" && {
         MOUNTED_CC="${@: -1} $MOUNTED_CC"
         test -z "$Y_NOCLEAN" && MOUNTED=$MOUNTED_CC
@@ -70,7 +96,6 @@ while [ -n "$1" ] ; do
     esac
     shift
 done
-test "xx" = "xx" && {
 # sync dev to current
 y_progress "Sync DEV system to current..."
 
@@ -95,17 +120,17 @@ test -z "$Y_NOMOUNT" && {
 
 # update build system on DEV: emerge --sync
 y_progress "Update gentoo build cache..."
-#y_run chroot $Y_DEV_MNT emerge --sync
+#y_run_ chroot $Y_DEV_MNT emerge --sync
 y_progress_end 0
 
 # check if it would build: emerge -pvuDN world
 y_progress "Check build..."
-y_run chroot $Y_DEV_MNT emerge -pvuDN world
+y_run_ chroot $Y_DEV_MNT emerge -pvuDN world
 y_progress_end 0
-}
+
 # build system on DEV: emerge -qubDN world
 y_progress "Build/update DEV system..."
-y_run chroot $Y_DEV_MNT emerge -qbuDN world
+y_run_ chroot $Y_DEV_MNT emerge -qbuDN world
 y_progress_end 0
 
 # update bootloader to boot new DEV
